Data Cleaning performed on medical data sourced from a Baltimore hospital. Publicly available dataset with over 10 key features. Lists insurance plans and billing amounts as well as medical condition.

In [1]:
import pandas as pd
import numpy as np 

data = pd.read_csv("/Users/judebaffoe-bonnie/Downloads/healthcare_dataset.csv")
data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,1/31/24,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2/2/24,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,8/20/19,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,8/26/19,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,9/22/22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,10/7/22,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,11/18/20,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,12/18/20,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,9/19/22,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,10/9/22,Penicillin,Abnormal

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

## Checking for blank cells and data spread

In [5]:
data.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [14]:
# # print(data[data.duplicated()])
data.describe()

# data['Billing Amount'].mean()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

Male and Female patient counts

In [20]:
data["Gender"].value_counts()

Male      27774
Female    27726
Name: Gender, dtype: int64

In [26]:
# standard date format
data['Date of Admission'] = pd.to_datetime(data['Date of Admission'], errors='coerce')
data['Discharge Date']    = pd.to_datetime(data['Discharge Date'],    errors='coerce')

data

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

## Adds columns for admission month, Qtr, and length of stay

In [42]:
#FEATURE ENGINEERING
data['admission_year'] = data['Date of Admission'].dt.year     #datetime functions:
data['admission_month_name'] = data['Date of Admission'].dt.month_name()
data['admission_quarter'] = data['Date of Admission'].dt.to_period('Q')

data['length_of_stay(days)'] = (data['Discharge Date'] - data['Date of Admission']).dt.days

data["Billing Amount"] = data["Billing Amount"].round(1)

data.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,...,Admission Type,Discharge Date,Medication,Test Results,admission_year,admission_month,admission_month_name,admission_quarter,length_of_stay,length_of_stay(days)
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.3,...,Urgent,2024-02-02,Paracetamol,Normal,2024,1,January,2024Q1,2,2
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.3,...,Emergency,2019-08-26,Ibuprofen,Inconclusive,2019,8,August,2019Q3,6,6
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.1,...,Emergency,2022-10-07,Aspirin,Normal,2022,9,September,2022Q3,15,15
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.8,...,Elective,2020-12-18,Ibuprofen,Abnormal,2020,11,November,2020Q4,30,30
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.3,...,Urgent,2022-10-09,Penicillin,Abnormal,2022,9,September,2022Q3,20,20
5,Emily Johnson,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.1,...,Urgent,2023-12-24,Ibuprofen,Normal,2023,12,December,2023Q4,4,4
6,Edward Edwards,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.9,...,Emergency,2020-11-15,Paracetamol,Inconclusive,2020,11,November,2020Q4,12,12
7,Christina Martinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.5,...,Emergency,2022-01-07,Paracetamol,Inconclusive,2021,12,December,2021Q4,10,10
8,Jasmine Aguilar,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.2,...,Elective,2020-07-14,Aspirin,Abnormal,2020,7,July,2020Q3,13,13
9,Christopher Berg,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.6,...,Elective,2021-06-22,Paracetamol,Inconclusive,2021,5,May,2021Q2,30,30

In [36]:
data['length_of_stay'].describe()

count    55500.000000
mean        15.509009
std          8.659600
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: length_of_stay, dtype: float64

In [ ]:
Makes sure all length of stay values are positive

In [41]:
data[data['length_of_stay'] <= 0]

Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results, admission_year, admission_month, admission_month_name, admission_quarter, length_of_stay, length_of_stay(days)]
Index: []

[0 rows x 21 columns]

In [51]:
data.drop('admission_month', axis=1, inplace=True)
data

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,admission_year,admission_month_name,admission_quarter,length_of_stay(days)
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.3,328,Urgent,2024-02-02,Paracetamol,Normal,2024,January,2024Q1,2
31,James Patterson,23,Female,A+,Arthritis,2019-11-03,Kristina Frazier,Cruz-Santiago,UnitedHealthcare,25835.3,108,Urgent,2019-11-29,Penicillin,Abnormal,2019,November,2019Q4,26
32,William Cooper,78,Male,AB-,Arthritis,2023-05-18,John Hartman,Group Duncan,Medicare,17993.2,245,Elective,2023-06-15,Penicillin,Normal,2023,May,2023Q2,28
33,Erin Ortega,43,Male,AB-,Cancer,2023-05-24,Heather Garcia,Lopez-Phillips,Medicare,21186.0,494,Elective,2023-06-03,Ibuprofen,Normal,2023,May,2023Q2,10
34,Nicole Rodriguez,30,Female,AB+,Diabetes,2020-01-17,Lynn Young,Poole Inc,Blue Cross,8408.9,285,Emergency,2020-02-10,Lipitor,Normal,2020,January,2020Q1,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.7,417,Elective,2020-09-15,Penicillin,Abnormal,2020,August,2020Q3,30
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.8,316,Elective,2020-02-01,Aspirin,Normal,2020,January,2020Q1,9
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.8,347,Urgent,2020-08-10,Ibuprofen,Abnormal,2020,July,2020Q3,28
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.1,321,Elective,2019-05-31,Ibuprofen,Abnormal,2019,May,2019Q2,6
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.1,448,Urgent,2024-04-29,Ibuprofen,Abnormal,2024,April,2024Q2,27

In [52]:
#saves cleaned dataset to new file "healthcare_data_cleaned"
data.to_csv("/Users/judebaffoe-bonnie/Downloads/healthcare_data_cleaned.csv")